### ISSUE TITLE
Animation rewind

### ISSUE THREAD

**Issue by kingjohnny** [TijsTT/justforshow#1]
I'm trying to rewind an animation when i scroll back to the top.
I've put this in my function. 
```
        name: 'slide-down',
        styleStart: 'transform: translateY(0px); opacity: 1;',
        styleEnd: 'transform: translateY(40px); opacity: 0;',
        duration: 100,
        delay: 0,
        offset: {
            start: 0,
            end: 250,
        },
        easing: 'ease-in-out',
        rewind: true,
        animatedrewind: true
```
Then i've put this div in my html. The animation works when i scroll down, but not backwards. What am i doing wrong?

`<div data-jfs="slide-down" data-jfs-animatedrewind="slide-down">Something in here</div>`

**Comment by TijsTT** [comment]
You can fix this by adding the data-jfs-offset-end attribute with a negative value! This is because the element is located on the top of the page and the breakpoint is calculated on the top side of the element. So, data-jfs-offset-end="-250" should work!
